### ISSUE TITLE
could not understand what need to do:

### ISSUE THREAD

**Issue by tom-github-com** [ITRS-Group/monitor-ninja#9]
6. Configure Ninja.
**_Edit the database connection settings in ninja/application/config/database.php and the path to the livestatus socket in /etc/op5/livestatus.yml_** 

8. Configure /etc/op5/*.yml files; livestatus.yml should point to your livestatus socket. Look at the other files so they match your system.

**Comment by geekmichael** [comment]
I am using naemon, here is my configuration:
```
[root@localhost ~]# cat /etc/op5/livestatus.yml 
path: /var/cache/naemon/live
```

**Comment by jacobbaungard** [comment]
Closing this. Let us know if the above did not answer your question @tom-github-com
